import '../styles/globals.scss'
import 'antd/dist/antd.css'

import type { AppProps } from 'next/app'
import { Layout } from 'layout'
import Head from 'next/head'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>CHECKLIST</title>
        <meta name="description" content="Generated by create next app" />
        <link type="image/x-icon" rel="shortcut icon" href="favicon.png" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  )
}

export default MyApp
