import { useLayout } from 'lib/hooks/useLayout'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/home.module.scss'

const Home: NextPage = () => {
  useLayout('Default')
  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>
  )
}

export default Home
